IntrepidGroup\ApiBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: IntrepidGroup\ApiBundle\Entity\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: string
            length: 255
        userId:
            type: integer
            column: user_id
    lifecycleCallbacks: {  }
    manyToOne:
        user:
            targetEntity: User
            inversedBy: comments
            joinColumn:
                name: user_id
                referencedColumnName: id